# Generated by Django 5.0 on 2023-12-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_purchaseorder_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalperformance',
            name='json_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
